server:
  port: 8085
king:
  rocketmq:
    serverUrl: localhostï¼š9876
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/king?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: neo_test
    password: neo@Test123
    hikari:
      auto-commit: true
      idle-timeout: 180000
      pool-name: tina.server-HikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
      maximum-pool-size: 10
      minimum-idle: 10
